name: Mergeback from main to backstage-integration

on:
  schedule:
    - cron: "20 8-22/2 * * 1-5"
  workflow_dispatch:

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: 'main'
          target_branch: 'backstage-integration'
          commit_message_template: 'chore: [Automated] Merged {source_ref} into target {target_branch}'
